apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: easyorder-app-core-hp 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easyorder-app-core-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
